apiVersion: v1
kind: Secret
metadata:
  name: user-app-urls
type: Opaque
data:
  DATABASE_HOST: cG9zdGdyZXMtZGItc2VydmljZS11c2Vy #postgres-db-service-user
  DATABASE_USER: YWRtaW4= #admin
  DATABASE_PASSWORD: YWRtaW4= #admin
  DATABASE_NAME: dXNlcg== #user
  DB_POOL_SIZE: OTA= #90
  SERVER_PORT: NTAwNTE= #50051
  METRICS_PORT: NDMyMQ== #4321
  MINIO_ROOT_USER: YWRtaW4= #admin
  MINIO_ROOT_PASSWORD: YWRtaW5hZG1pbg== #adminadmin
  MINIO_URL: bWluaW8tc2VydmljZTo5MDAw #minio-service:9000
  MINIO_BUCKET: Ym94aW5nLWxhbmQ= #boxing-land
  AUTH_SERVICE_URL: YXV0aC1zZXJ2aWNlOjUwMDUy #auth-service:50052