apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  labels:
    name: user-app
    app: user-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-grpc
  template:
    metadata:
      labels:
        app: user-grpc
    spec:
      containers:
      - name: user-grpc
        image: emurashin/user-service:latest
        imagePullPolicy: Always
        ports:
          - name: user-service
            containerPort: 50051
          - name: user-monitoring
            containerPort: 4321
        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: DATABASE_HOST
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: DATABASE_USER
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: DATABASE_PASSWORD
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: DATABASE_NAME
          - name: DB_POOL_SIZE
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: DB_POOL_SIZE
          - name: SERVER_PORT
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: SERVER_PORT
          - name: METRICS_PORT
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: METRICS_PORT
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: MINIO_ROOT_USER
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: MINIO_ROOT_PASSWORD
          - name: MINIO_URL
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: MINIO_URL
          - name: MINIO_BUCKET
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: MINIO_BUCKET
          - name: AUTH_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: user-app-urls
                key: AUTH_SERVICE_URL