apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-user
  labels:
    name: postgres-db-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db-user
  template:
    metadata:
      labels:
        app: postgres-db-user
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: user-db-credentials
                key: user

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-db-credentials
                key: password

          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: user-db-credentials
                key: db