apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service-user
  labels:
    service: postgres-db-service-user
spec:
  selector:
    app: postgres-db-user
  ports:
    - name: tcp-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer