apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
#  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'auth-monitoring'
        scrape_interval: 10s
        metrics_path: '/'
        static_configs:
          - targets: [ 'auth-monitoring:4322' ]
            
      - job_name: 'user-monitoring'
        scrape_interval: 10s
        metrics_path: '/'
        static_configs:
          - targets: ['user-monitoring:4321']
            
      - job_name: 'gateway-monitoring'
        scrape_interval: 10s
        metrics_path: '/metrics'
        static_configs:
          - targets: [ 'gateway-service:8000' ]