apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-service
spec:
  selector:
    app: gateway-api
  ports:
    - name: http
      port: 8000
      nodePort: 30080
  type: NodePort