apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  minio_url: bG9jYWxob3N0OjkwMDA= #localhost:9000
  minio_bucket: Ym94aW5nLWxhbmQ= #boxing-land
  minio_root_user: YWRtaW4= #admin
  minio_root_password: YWRtaW5hZG1pbg== #adminadmin
