apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service-auth
  labels:
    service: postgres-db-service-auth
spec:
  selector:
    app: postgres-db-auth
  ports:
    - name: tcp-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
